/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tlal (https://sketchfab.com/tlal)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/spyro-reignited-trilogy-7a7d469a46474e26a540bec12d3b6294
title: Spyro - Reignited trilogy
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Dragon(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/dragon.gltf')
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_Spyro_65" position={[0, 0.44, -0.24]} rotation={[1.37, 0, 0]} scale={0.25}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Spyro} skeleton={nodes.Object_73.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dragon.gltf')
