/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: JaDe.Dfr (https://sketchfab.com/JaDe.Dfr)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cute-isometric-room-59429ffd87474792b15132a7df4c965f
title: Cute Isometric Room ✿
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Room(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/room.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="c6cba57d353a400bb00be05dde2d5593fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Part_009_L3" position={[91.34, 27.25, 8.14]} rotation={[0, 0, -Math.PI / 10]} />
                <group name="polySurface269" position={[-1.65, 36.15, -39.84]}>
                  <mesh name="polySurface269_feu_0" geometry={nodes.polySurface269_feu_0.geometry} material={materials.material_24} />
                </group>
                <group name="polySurface270" position={[-41.3, 80.52, 27.58]}>
                  <mesh name="polySurface270_feu_0" geometry={nodes.polySurface270_feu_0.geometry} material={materials.material_24} />
                </group>
                <group name="polySurface271" position={[-0.15, 36.16, -38.25]}>
                  <mesh name="polySurface271_feu_0" geometry={nodes.polySurface271_feu_0.geometry} material={materials.material_24} />
                </group>
                <group name="polySurface272" position={[-0.66, 35.22, -41.61]}>
                  <mesh name="polySurface272_feu_0" geometry={nodes.polySurface272_feu_0.geometry} material={materials.material_24} />
                </group>
                <group name="polySurface273" position={[-40.67, 82.04, 25.64]}>
                  <mesh name="polySurface273_feu_0" geometry={nodes.polySurface273_feu_0.geometry} material={materials.material_24} />
                </group>
                <group name="pCube1" position={[0, 0, 0.08]}>
                  <mesh name="pCube1_brun_0" geometry={nodes.pCube1_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube2">
                  <mesh name="pCube2_rose_0" geometry={nodes.pCube2_rose_0.geometry} material={materials.rose} />
                </group>
                <group name="pCube3">
                  <mesh name="pCube3_rose_0" geometry={nodes.pCube3_rose_0.geometry} material={materials.rose} />
                  <mesh name="pCube3_lila_0" geometry={nodes.pCube3_lila_0.geometry} material={materials.lila} />
                  <mesh name="pCube3_brun_0" geometry={nodes.pCube3_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube17">
                  <mesh name="pCube17_beige_0" geometry={nodes.pCube17_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCylinder1" position={[-2, 0, -3.25]}>
                  <mesh name="pCylinder1_blanc_0" geometry={nodes.pCylinder1_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCylinder4">
                  <mesh name="pCylinder4_blanc_0" geometry={nodes.pCylinder4_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder4_beige_0" geometry={nodes.pCylinder4_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCylinder16">
                  <mesh name="pCylinder16_brun_0" geometry={nodes.pCylinder16_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCylinder16_blanc_0" geometry={nodes.pCylinder16_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder16_brun_fonc��_0" geometry={nodes['pCylinder16_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder16_vert_0" geometry={nodes.pCylinder16_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pCube24">
                  <mesh name="pCube24_beige_0" geometry={nodes.pCube24_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCube24_blanc_0" geometry={nodes.pCube24_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCube24_brun_0" geometry={nodes.pCube24_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube25" position={[0, 0, 44.52]} scale={[1, 1, 2.01]}>
                  <mesh name="pCube25_blanc_0" geometry={nodes.pCube25_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere8">
                  <mesh name="pSphere8_transparence_0" geometry={nodes.pSphere8_transparence_0.geometry} material={materials.transparence} />
                  <mesh name="pSphere8_eau_0" geometry={nodes.pSphere8_eau_0.geometry} material={materials.material} />
                  <mesh name="pSphere8_vert_0" geometry={nodes.pSphere8_vert_0.geometry} material={materials.vert} />
                  <mesh name="pSphere8_brun_0" geometry={nodes.pSphere8_brun_0.geometry} material={materials.brun} />
                  <mesh name="pSphere8_lambert1_0" geometry={nodes.pSphere8_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="book">
                  <mesh name="book_blanc_0" geometry={nodes.book_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="book_lila_0" geometry={nodes.book_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube50">
                  <mesh name="pCube50_blanc_0" geometry={nodes.pCube50_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube51">
                  <mesh name="pCube51_blanc_0" geometry={nodes.pCube51_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere18" position={[-5.12, 0.25, 30.03]} rotation={[-0.33, -0.3, -0.15]}>
                  <mesh name="pSphere18_brun_0" geometry={nodes.pSphere18_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube53">
                  <mesh name="pCube53_brun_0" geometry={nodes.pCube53_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube53_blanc_0" geometry={nodes.pCube53_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube55" position={[0, -0.07, 0]}>
                  <mesh name="pCube55_blanc_0" geometry={nodes.pCube55_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube56" position={[0, -0.13, 0]}>
                  <mesh name="pCube56_blanc_0" geometry={nodes.pCube56_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube57">
                  <mesh name="pCube57_brun_0" geometry={nodes.pCube57_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube57_blanc_0" geometry={nodes.pCube57_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCone13">
                  <group name="polySurface200">
                    <mesh name="polySurface200_blanc_0" geometry={nodes.polySurface200_blanc_0.geometry} material={materials.blanc} />
                  </group>
                  <group name="polySurface201" position={[0, -50.5, 0.04]} scale={1.71}>
                    <mesh name="polySurface201_light_0" geometry={nodes.polySurface201_light_0.geometry} material={materials.light} />
                  </group>
                  <group name="polySurface202">
                    <mesh name="polySurface202_blanc_0" geometry={nodes.polySurface202_blanc_0.geometry} material={materials.blanc} />
                  </group>
                </group>
                <group name="pCube58">
                  <mesh name="pCube58_brun_0" geometry={nodes.pCube58_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="extrudedSurface4">
                  <mesh name="extrudedSurface4_blanc_0" geometry={nodes.extrudedSurface4_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube59">
                  <mesh name="pCube59_blanc_0" geometry={nodes.pCube59_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="polySurface152">
                  <mesh name="polySurface152_blanc_0" geometry={nodes.polySurface152_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface152_bleu_0" geometry={nodes.polySurface152_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="Plant_7">
                  <mesh name="Plant_7_vert_0" geometry={nodes.Plant_7_vert_0.geometry} material={materials.vert} />
                  <mesh name="Plant_7_brun_0" geometry={nodes.Plant_7_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube61">
                  <mesh name="pCube61_brun_0" geometry={nodes.pCube61_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube61_blanc_0" geometry={nodes.pCube61_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere28">
                  <mesh name="pSphere28_light_0" geometry={nodes.pSphere28_light_0.geometry} material={materials.light} />
                  <mesh name="pSphere28_blanc_0" geometry={nodes.pSphere28_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube62" position={[-16.37, -5.53, 14.72]} scale={1.46}>
                  <mesh name="pCube62_blanc_0" geometry={nodes.pCube62_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCube62_rose_0" geometry={nodes.pCube62_rose_0.geometry} material={materials.rose} />
                </group>
                <group name="pCube67">
                  <mesh name="pCube67_lila_0" geometry={nodes.pCube67_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube68">
                  <mesh name="pCube68_brun_0" geometry={nodes.pCube68_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube68_lila_0" geometry={nodes.pCube68_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube69">
                  <mesh name="pCube69_brun_0" geometry={nodes.pCube69_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube69_lila_0" geometry={nodes.pCube69_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube70">
                  <mesh name="pCube70_brun_0" geometry={nodes.pCube70_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCube70_lila_0" geometry={nodes.pCube70_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="polySurface155">
                  <mesh name="polySurface155_blanc_0" geometry={nodes.polySurface155_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface155_jaune_0" geometry={nodes.polySurface155_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="pCube71">
                  <mesh name="pCube71_beige_0" geometry={nodes.pCube71_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCube71_blanc_0" geometry={nodes.pCube71_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="polySurface179">
                  <mesh name="polySurface179_beige_0" geometry={nodes.polySurface179_beige_0.geometry} material={materials.beige} />
                  <mesh name="polySurface179_blanc_0" geometry={nodes.polySurface179_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface179_brun_0" geometry={nodes.polySurface179_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="polySurface182">
                  <mesh name="polySurface182_blanc_0" geometry={nodes.polySurface182_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface182_jaune_0" geometry={nodes.polySurface182_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="polySurface183">
                  <mesh name="polySurface183_blanc_0" geometry={nodes.polySurface183_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface183_bleu_0" geometry={nodes.polySurface183_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="polySurface184">
                  <mesh name="polySurface184_blanc_0" geometry={nodes.polySurface184_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface184_jaune_0" geometry={nodes.polySurface184_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="polySurface185">
                  <mesh name="polySurface185_blanc_0" geometry={nodes.polySurface185_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface185_rose_0" geometry={nodes.polySurface185_rose_0.geometry} material={materials.rose} />
                </group>
                <group name="polySurface186">
                  <mesh name="polySurface186_blanc_0" geometry={nodes.polySurface186_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface186_bleu_0" geometry={nodes.polySurface186_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="polySurface186_jaune_0" geometry={nodes.polySurface186_jaune_0.geometry} material={materials.jaune} />
                  <mesh name="polySurface186_lila_0" geometry={nodes.polySurface186_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="polySurface187">
                  <mesh name="polySurface187_blanc_0" geometry={nodes.polySurface187_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface187_rose_0" geometry={nodes.polySurface187_rose_0.geometry} material={materials.rose} />
                  <mesh name="polySurface187_bleu_0" geometry={nodes.polySurface187_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="polySurface187_lila_0" geometry={nodes.polySurface187_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube79">
                  <mesh name="pCube79_beige_0" geometry={nodes.pCube79_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCube79_turquoise_0" geometry={nodes.pCube79_turquoise_0.geometry} material={materials.turquoise} />
                  <mesh name="pCube79_jaune_0" geometry={nodes.pCube79_jaune_0.geometry} material={materials.jaune} />
                  <mesh name="pCube79_rose_0" geometry={nodes.pCube79_rose_0.geometry} material={materials.rose} />
                </group>
                <group name="Mesh1">
                  <mesh name="Mesh1_poisson2_0" geometry={nodes.Mesh1_poisson2_0.geometry} material={materials.poisson2} />
                  <mesh name="Mesh1_transparence_0" geometry={nodes.Mesh1_transparence_0.geometry} material={materials.transparence} />
                  <mesh name="Mesh1_eau_0" geometry={nodes.Mesh1_eau_0.geometry} material={materials.material} />
                  <mesh name="Mesh1_poisson1_0" geometry={nodes.Mesh1_poisson1_0.geometry} material={materials.poisson1} />
                </group>
                <group name="pSphere31">
                  <mesh name="pSphere31_vert_0" geometry={nodes.pSphere31_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pCylinder47">
                  <mesh name="pCylinder47_blanc_0" geometry={nodes.pCylinder47_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere32">
                  <mesh name="pSphere32_vert_0" geometry={nodes.pSphere32_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere33">
                  <mesh name="pSphere33_vert_0" geometry={nodes.pSphere33_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere34">
                  <mesh name="pSphere34_vert_0" geometry={nodes.pSphere34_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere35">
                  <mesh name="pSphere35_vert_0" geometry={nodes.pSphere35_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere36">
                  <mesh name="pSphere36_vert_0" geometry={nodes.pSphere36_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere37">
                  <mesh name="pSphere37_vert_0" geometry={nodes.pSphere37_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere38">
                  <mesh name="pSphere38_vert_0" geometry={nodes.pSphere38_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere39">
                  <mesh name="pSphere39_vert_0" geometry={nodes.pSphere39_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere41">
                  <mesh name="pSphere41_vert_0" geometry={nodes.pSphere41_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere42">
                  <mesh name="pSphere42_vert_0" geometry={nodes.pSphere42_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere43">
                  <mesh name="pSphere43_vert_0" geometry={nodes.pSphere43_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere44">
                  <mesh name="pSphere44_vert_0" geometry={nodes.pSphere44_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere45">
                  <mesh name="pSphere45_vert_0" geometry={nodes.pSphere45_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere46">
                  <mesh name="pSphere46_vert_0" geometry={nodes.pSphere46_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere47">
                  <mesh name="pSphere47_vert_0" geometry={nodes.pSphere47_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pCube89" position={[-0.25, 0.71, 0]}>
                  <mesh name="pCube89_blanc_0" geometry={nodes.pCube89_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube90" position={[0, 0.6, 0.29]}>
                  <mesh name="pCube90_blanc_0" geometry={nodes.pCube90_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="extrudedSurface9">
                  <mesh name="extrudedSurface9_blanc_0" geometry={nodes.extrudedSurface9_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere48">
                  <mesh name="pSphere48_light_0" geometry={nodes.pSphere48_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere49">
                  <mesh name="pSphere49_light_0" geometry={nodes.pSphere49_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere50">
                  <mesh name="pSphere50_light_0" geometry={nodes.pSphere50_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere51">
                  <mesh name="pSphere51_light_0" geometry={nodes.pSphere51_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere52">
                  <mesh name="pSphere52_light_0" geometry={nodes.pSphere52_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere53">
                  <mesh name="pSphere53_light_0" geometry={nodes.pSphere53_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere54">
                  <mesh name="pSphere54_light_0" geometry={nodes.pSphere54_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere55">
                  <mesh name="pSphere55_light_0" geometry={nodes.pSphere55_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere56">
                  <mesh name="pSphere56_light_0" geometry={nodes.pSphere56_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere57">
                  <mesh name="pSphere57_light_0" geometry={nodes.pSphere57_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere58">
                  <mesh name="pSphere58_light_0" geometry={nodes.pSphere58_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere59">
                  <mesh name="pSphere59_light_0" geometry={nodes.pSphere59_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere60">
                  <mesh name="pSphere60_light_0" geometry={nodes.pSphere60_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere61">
                  <mesh name="pSphere61_light_0" geometry={nodes.pSphere61_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere62">
                  <mesh name="pSphere62_light_0" geometry={nodes.pSphere62_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere63">
                  <mesh name="pSphere63_light_0" geometry={nodes.pSphere63_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere64">
                  <mesh name="pSphere64_light_0" geometry={nodes.pSphere64_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere65">
                  <mesh name="pSphere65_light_0" geometry={nodes.pSphere65_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere66">
                  <mesh name="pSphere66_light_0" geometry={nodes.pSphere66_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere67">
                  <mesh name="pSphere67_light_0" geometry={nodes.pSphere67_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere68">
                  <mesh name="pSphere68_light_0" geometry={nodes.pSphere68_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere69">
                  <mesh name="pSphere69_light_0" geometry={nodes.pSphere69_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere70">
                  <mesh name="pSphere70_light_0" geometry={nodes.pSphere70_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere71">
                  <mesh name="pSphere71_light_0" geometry={nodes.pSphere71_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere72">
                  <mesh name="pSphere72_light_0" geometry={nodes.pSphere72_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere73">
                  <mesh name="pSphere73_light_0" geometry={nodes.pSphere73_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere74">
                  <mesh name="pSphere74_light_0" geometry={nodes.pSphere74_light_0.geometry} material={materials.light} />
                </group>
                <group name="polySurface188">
                  <mesh name="polySurface188_beige_0" geometry={nodes.polySurface188_beige_0.geometry} material={materials.beige} />
                  <mesh name="polySurface188_blanc_0" geometry={nodes.polySurface188_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface188_noir_0" geometry={nodes.polySurface188_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pSphere75">
                  <mesh name="pSphere75_light_0" geometry={nodes.pSphere75_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere76">
                  <mesh name="pSphere76_light_0" geometry={nodes.pSphere76_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere77">
                  <mesh name="pSphere77_light_0" geometry={nodes.pSphere77_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere78">
                  <mesh name="pSphere78_light_0" geometry={nodes.pSphere78_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere79">
                  <mesh name="pSphere79_light_0" geometry={nodes.pSphere79_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere80">
                  <mesh name="pSphere80_light_0" geometry={nodes.pSphere80_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere81">
                  <mesh name="pSphere81_light_0" geometry={nodes.pSphere81_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere82">
                  <mesh name="pSphere82_light_0" geometry={nodes.pSphere82_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere83">
                  <mesh name="pSphere83_light_0" geometry={nodes.pSphere83_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere84">
                  <mesh name="pSphere84_light_0" geometry={nodes.pSphere84_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere85">
                  <mesh name="pSphere85_light_0" geometry={nodes.pSphere85_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere86">
                  <mesh name="pSphere86_light_0" geometry={nodes.pSphere86_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere87">
                  <mesh name="pSphere87_light_0" geometry={nodes.pSphere87_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere88">
                  <mesh name="pSphere88_light_0" geometry={nodes.pSphere88_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere89">
                  <mesh name="pSphere89_light_0" geometry={nodes.pSphere89_light_0.geometry} material={materials.light} />
                </group>
                <group name="pCone18">
                  <mesh name="pCone18_vert_fonc��_0" geometry={nodes['pCone18_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere97">
                  <mesh name="pSphere97_vert_pale_0" geometry={nodes.pSphere97_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere98">
                  <mesh name="pSphere98_vert_pale_0" geometry={nodes.pSphere98_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere99">
                  <mesh name="pSphere99_vert_pale_0" geometry={nodes.pSphere99_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere100">
                  <mesh name="pSphere100_vert_pale_0" geometry={nodes.pSphere100_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere101">
                  <mesh name="pSphere101_vert_pale_0" geometry={nodes.pSphere101_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere102">
                  <mesh name="pSphere102_vert_pale_0" geometry={nodes.pSphere102_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere103">
                  <mesh name="pSphere103_vert_pale_0" geometry={nodes.pSphere103_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere104">
                  <mesh name="pSphere104_vert_pale_0" geometry={nodes.pSphere104_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere105">
                  <mesh name="pSphere105_vert_pale_0" geometry={nodes.pSphere105_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere106">
                  <mesh name="pSphere106_vert_pale_0" geometry={nodes.pSphere106_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere107">
                  <mesh name="pSphere107_vert_pale_0" geometry={nodes.pSphere107_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere108">
                  <mesh name="pSphere108_vert_pale_0" geometry={nodes.pSphere108_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere109">
                  <mesh name="pSphere109_vert_pale_0" geometry={nodes.pSphere109_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere110">
                  <mesh name="pSphere110_vert_pale_0" geometry={nodes.pSphere110_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere111">
                  <mesh name="pSphere111_vert_pale_0" geometry={nodes.pSphere111_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere112">
                  <mesh name="pSphere112_vert_pale_0" geometry={nodes.pSphere112_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pSphere113">
                  <mesh name="pSphere113_vert_fonc��_0" geometry={nodes['pSphere113_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere114">
                  <mesh name="pSphere114_vert_fonc��_0" geometry={nodes['pSphere114_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere115">
                  <mesh name="pSphere115_vert_fonc��_0" geometry={nodes['pSphere115_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere116">
                  <mesh name="pSphere116_vert_fonc��_0" geometry={nodes['pSphere116_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere117">
                  <mesh name="pSphere117_vert_fonc��_0" geometry={nodes['pSphere117_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere118">
                  <mesh name="pSphere118_vert_fonc��_0" geometry={nodes['pSphere118_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere119">
                  <mesh name="pSphere119_vert_0" geometry={nodes.pSphere119_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere120">
                  <mesh name="pSphere120_vert_0" geometry={nodes.pSphere120_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere121">
                  <mesh name="pSphere121_vert_0" geometry={nodes.pSphere121_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere122">
                  <mesh name="pSphere122_vert_0" geometry={nodes.pSphere122_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere123">
                  <mesh name="pSphere123_vert_fonc��_0" geometry={nodes['pSphere123_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere124">
                  <mesh name="pSphere124_vert_fonc��_0" geometry={nodes['pSphere124_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pSphere125">
                  <mesh name="pSphere125_vert_0" geometry={nodes.pSphere125_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere126">
                  <mesh name="pSphere126_vert_0" geometry={nodes.pSphere126_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pSphere127">
                  <mesh name="pSphere127_vert_pale_0" geometry={nodes.pSphere127_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pCube91" position={[-0.17, -0.68, 1.39]} rotation={[-0.02, -0.01, -0.01]}>
                  <mesh name="pCube91_beige_0" geometry={nodes.pCube91_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCube91_blanc_0" geometry={nodes.pCube91_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="polySurface189">
                  <mesh name="polySurface189_beige_0" geometry={nodes.polySurface189_beige_0.geometry} material={materials.beige} />
                  <mesh name="polySurface189_blanc_0" geometry={nodes.polySurface189_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface189_noir_0" geometry={nodes.polySurface189_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="polySurface190">
                  <mesh name="polySurface190_beige_0" geometry={nodes.polySurface190_beige_0.geometry} material={materials.beige} />
                  <mesh name="polySurface190_blanc_0" geometry={nodes.polySurface190_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="Mesh2">
                  <mesh name="Mesh2_musique_0" geometry={nodes.Mesh2_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="noteMesh1">
                  <mesh name="noteMesh1_musique_0" geometry={nodes.noteMesh1_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh4">
                  <mesh name="Mesh4_musique_0" geometry={nodes.Mesh4_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh5">
                  <mesh name="Mesh5_musique_0" geometry={nodes.Mesh5_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh6">
                  <mesh name="Mesh6_musique_0" geometry={nodes.Mesh6_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh7">
                  <mesh name="Mesh7_musique_0" geometry={nodes.Mesh7_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh8">
                  <mesh name="Mesh8_musique_0" geometry={nodes.Mesh8_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Neck01">
                  <mesh name="Neck01_beige_0" geometry={nodes.Neck01_beige_0.geometry} material={materials.beige} />
                  <mesh name="Neck01_turquoise_0" geometry={nodes.Neck01_turquoise_0.geometry} material={materials.turquoise} />
                  <mesh name="Neck01_pasted__turquoise_0" geometry={nodes.Neck01_pasted__turquoise_0.geometry} material={materials.pasted__turquoise} />
                </group>
                <group name="pCube93">
                  <mesh name="pCube93_brun_0" geometry={nodes.pCube93_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCube101">
                  <mesh name="pCube101_blanc_0" geometry={nodes.pCube101_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCylinder51">
                  <mesh name="pCylinder51_brun_0" geometry={nodes.pCylinder51_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCylinder51_blanc_0" geometry={nodes.pCylinder51_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder51_vert_0" geometry={nodes.pCylinder51_vert_0.geometry} material={materials.vert} />
                </group>
                <group name="pCube104">
                  <mesh name="pCube104_noir_0" geometry={nodes.pCube104_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube105">
                  <mesh name="pCube105_blanc_0" geometry={nodes.pCube105_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCylinder52">
                  <mesh name="pCylinder52_beige_0" geometry={nodes.pCylinder52_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCylinder52_brun_0" geometry={nodes.pCylinder52_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCylinder53">
                  <mesh name="pCylinder53_beige_0" geometry={nodes.pCylinder53_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCylinder53_brun_0" geometry={nodes.pCylinder53_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCylinder54">
                  <mesh name="pCylinder54_blanc_0" geometry={nodes.pCylinder54_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder54_vert_0" geometry={nodes.pCylinder54_vert_0.geometry} material={materials.vert} />
                  <mesh name="pCylinder54_vert_fonc��_0" geometry={nodes['pCylinder54_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pCylinder55" position={[-21.83, 46.82, 44.79]} scale={0.44}>
                  <mesh name="pCylinder55_lila_0" geometry={nodes.pCylinder55_lila_0.geometry} material={materials.lila} />
                  <mesh name="pCylinder55_brun_fonc��_0" geometry={nodes['pCylinder55_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder55_vert_0" geometry={nodes.pCylinder55_vert_0.geometry} material={materials.vert} />
                  <mesh name="pCylinder55_vert_fonc��_0" geometry={nodes['pCylinder55_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pPlane2">
                  <mesh name="pPlane2_jaune_0" geometry={nodes.pPlane2_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="pPlane3">
                  <mesh name="pPlane3_jaune_0" geometry={nodes.pPlane3_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="pPlane4">
                  <mesh name="pPlane4_jaune_0" geometry={nodes.pPlane4_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="pPlane8" position={[-0.9, 0.54, -0.58]}>
                  <mesh name="pPlane8_plafond_0" geometry={nodes.pPlane8_plafond_0.geometry} material={materials.plafond} />
                </group>
                <group name="Plant_11">
                  <mesh name="Plant_11_vert_fonc��_0" geometry={nodes['Plant_11_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                  <mesh name="Plant_11_brun_0" geometry={nodes.Plant_11_brun_0.geometry} material={materials.brun} />
                </group>
                <group name="pCylinder64" position={[0, 0.23, 0]}>
                  <mesh name="pCylinder64_blanc_0" geometry={nodes.pCylinder64_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder64_brun_fonc��_0" geometry={nodes['pCylinder64_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                </group>
                <group name="pCylinder65" position={[0, 0.32, -0.33]}>
                  <mesh name="pCylinder65_brun_0" geometry={nodes.pCylinder65_brun_0.geometry} material={materials.brun} />
                  <mesh name="pCylinder65_blanc_0" geometry={nodes.pCylinder65_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder65_brun_fonc��_0" geometry={nodes['pCylinder65_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder65_vert_pale_0" geometry={nodes.pCylinder65_vert_pale_0.geometry} material={materials.vert_pale} />
                </group>
                <group name="pCube119">
                  <mesh name="pCube119_beige_0" geometry={nodes.pCube119_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="commode">
                  <mesh name="commode_beige_0" geometry={nodes.commode_beige_0.geometry} material={materials.beige} />
                  <mesh name="commode_blanc_0" geometry={nodes.commode_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="polySurface191">
                  <mesh name="polySurface191_blanc_0" geometry={nodes.polySurface191_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface191_bleu_0" geometry={nodes.polySurface191_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="polySurface191_jaune_0" geometry={nodes.polySurface191_jaune_0.geometry} material={materials.jaune} />
                  <mesh name="polySurface191_lila_0" geometry={nodes.polySurface191_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pSphere128">
                  <mesh name="pSphere128_vert_0" geometry={nodes.pSphere128_vert_0.geometry} material={materials.vert} />
                  <mesh name="pSphere128_blanc_0" geometry={nodes.pSphere128_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pSphere128_brun_fonc��_0" geometry={nodes['pSphere128_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pSphere128_vert_fonc��_0" geometry={nodes['pSphere128_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="BedMesh" position={[-36.07, 48.27, -88.18]} scale={25.54}>
                  <group name="polySurface193">
                    <mesh name="polySurface193_blanc_0" geometry={nodes.polySurface193_blanc_0.geometry} material={materials.blanc} />
                  </group>
                  <group name="polySurface194">
                    <mesh name="polySurface194_beige_0" geometry={nodes.polySurface194_beige_0.geometry} material={materials.beige} />
                  </group>
                  <group name="polySurface195">
                    <mesh name="polySurface195_beige_0" geometry={nodes.polySurface195_beige_0.geometry} material={materials.beige} />
                  </group>
                  <group name="polySurface196">
                    <mesh name="polySurface196_beige_0" geometry={nodes.polySurface196_beige_0.geometry} material={materials.beige} />
                  </group>
                  <group name="polySurface197" position={[0.01, -0.14, 0.09]} rotation={[-0.04, 0.02, 0.07]}>
                    <mesh name="polySurface197_rose_0" geometry={nodes.polySurface197_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface198" position={[-0.01, 0.01, 0.09]}>
                    <mesh name="polySurface198_jaune_0" geometry={nodes.polySurface198_jaune_0.geometry} material={materials.jaune} />
                  </group>
                  <group name="polySurface199" position={[0.04, 0.03, 0.07]}>
                    <mesh name="polySurface199_bleu_0" geometry={nodes.polySurface199_bleu_0.geometry} material={materials.bleu} />
                  </group>
                  <group name="polySurface218" position={[-0.15, 0.76, 2.69]} rotation={[0.59, 0.2, 1.3]} scale={0.77}>
                    <mesh name="polySurface218_jaune_0" geometry={nodes.polySurface218_jaune_0.geometry} material={materials.jaune} />
                  </group>
                </group>
                <group name="pCube125">
                  <mesh name="pCube125_blanc_0" geometry={nodes.pCube125_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube126">
                  <mesh name="pCube126_blanc_0" geometry={nodes.pCube126_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube138">
                  <mesh name="pCube138_blanc_0" geometry={nodes.pCube138_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="polySurface192">
                  <mesh name="polySurface192_blanc_0" geometry={nodes.polySurface192_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface192_rose_0" geometry={nodes.polySurface192_rose_0.geometry} material={materials.rose} />
                  <mesh name="polySurface192_lila_0" geometry={nodes.polySurface192_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCube139">
                  <mesh name="pCube139_turquoise_0" geometry={nodes.pCube139_turquoise_0.geometry} material={materials.turquoise} />
                </group>
                <group name="pCube140">
                  <mesh name="pCube140_bleu_0" geometry={nodes.pCube140_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="pPlane10">
                  <mesh name="pPlane10_jaune_0" geometry={nodes.pPlane10_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="pCylinder66">
                  <mesh name="pCylinder66_noir_0" geometry={nodes.pCylinder66_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pSphere129">
                  <mesh name="pSphere129_light_0" geometry={nodes.pSphere129_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere130">
                  <mesh name="pSphere130_light_0" geometry={nodes.pSphere130_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere131">
                  <mesh name="pSphere131_light_0" geometry={nodes.pSphere131_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere132">
                  <mesh name="pSphere132_light_0" geometry={nodes.pSphere132_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere133">
                  <mesh name="pSphere133_light_0" geometry={nodes.pSphere133_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere134">
                  <mesh name="pSphere134_light_0" geometry={nodes.pSphere134_light_0.geometry} material={materials.light} />
                </group>
                <group name="pSphere135">
                  <mesh name="pSphere135_light_0" geometry={nodes.pSphere135_light_0.geometry} material={materials.light} />
                </group>
                <group name="pCylinder67">
                  <mesh name="pCylinder67_noir_0" geometry={nodes.pCylinder67_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube141">
                  <mesh name="pCube141_blanc_0" geometry={nodes.pCube141_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pCube142">
                  <mesh name="pCube142_beige_0" geometry={nodes.pCube142_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube143">
                  <mesh name="pCube143_beige_0" geometry={nodes.pCube143_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube152">
                  <mesh name="pCube152_beige_0" geometry={nodes.pCube152_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCylinder70" position={[0.56, -0.34, 1.25]}>
                  <mesh name="pCylinder70_turquoise_0" geometry={nodes.pCylinder70_turquoise_0.geometry} material={materials.turquoise} />
                </group>
                <group name="pSphere136" position={[0, 0.22, 0]}>
                  <mesh name="pSphere136_noir_0" geometry={nodes.pSphere136_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pPlane11" position={[-0.76, -0.37, 0]}>
                  <mesh name="pPlane11_lila_0" geometry={nodes.pPlane11_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pCylinder71" position={[-37.92, 3.43, 2.68]} scale={[3.19, 3.4, 3.19]}>
                  <mesh name="pCylinder71_lila_0" geometry={nodes.pCylinder71_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="pSphere137" position={[-35.88, 35.55, -2.68]} scale={1.18}>
                  <mesh name="pSphere137_light_0" geometry={nodes.pSphere137_light_0.geometry} material={materials.light} />
                </group>
                <group name="pPlatonic1" position={[-38.93, 4.12, 2.31]}>
                  <mesh name="pPlatonic1_blanc_0" geometry={nodes.pPlatonic1_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic2" position={[-37.37, 5.21, 3.75]} scale={1.07}>
                  <mesh name="pPlatonic2_blanc_0" geometry={nodes.pPlatonic2_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic3" position={[-39.38, 5.6, 2.98]} rotation={[0.17, 0.28, 0.89]} scale={1.3}>
                  <mesh name="pPlatonic3_blanc_0" geometry={nodes.pPlatonic3_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic4" position={[-36.39, 6.12, 1.99]}>
                  <mesh name="pPlatonic4_blanc_0" geometry={nodes.pPlatonic4_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic5" position={[-37.76, 6.91, 1.64]} rotation={[0, 0, 0.42]}>
                  <mesh name="pPlatonic5_blanc_0" geometry={nodes.pPlatonic5_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic6" position={[-33.2, 3.31, 5.28]} rotation={[0, 0, -0.3]} scale={0.85}>
                  <mesh name="pPlatonic6_blanc_0" geometry={nodes.pPlatonic6_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic7" position={[-32.75, 3.36, -0.21]} rotation={[0, 0, 0.1]} scale={1.06}>
                  <mesh name="pPlatonic7_blanc_0" geometry={nodes.pPlatonic7_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic8" position={[-37.07, 3.38, -1.04]} rotation={[0, 0, -0.35]} scale={1.25}>
                  <mesh name="pPlatonic8_blanc_0" geometry={nodes.pPlatonic8_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pSphere140" position={[-2, 0, -3.25]}>
                  <mesh name="pSphere140_eau_0" geometry={nodes.pSphere140_eau_0.geometry} material={materials.material} />
                  <mesh name="pSphere140_beige_0" geometry={nodes.pSphere140_beige_0.geometry} material={materials.beige} />
                  <mesh name="pSphere140_blanc_0" geometry={nodes.pSphere140_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pSphere140_pasted__rose1_0" geometry={nodes.pSphere140_pasted__rose1_0.geometry} material={materials.pasted__rose1} />
                  <mesh name="pSphere140_bleu_0" geometry={nodes.pSphere140_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="pSphere140_brun_0" geometry={nodes.pSphere140_brun_0.geometry} material={materials.brun} />
                  <mesh name="pSphere140_lambert1_0" geometry={nodes.pSphere140_lambert1_0.geometry} material={materials.lambert1} />
                  <mesh name="pSphere140_rose_0" geometry={nodes.pSphere140_rose_0.geometry} material={materials.rose} />
                  <mesh name="pSphere140_pasted__rose_0" geometry={nodes.pSphere140_pasted__rose_0.geometry} material={materials.pasted__rose} />
                </group>
                <group name="pCylinder83" position={[-48.03, 33.07, -27.83]} scale={1.42}>
                  <mesh name="pCylinder83_vert_0" geometry={nodes.pCylinder83_vert_0.geometry} material={materials.vert} />
                  <mesh name="pCylinder83_brun_fonc��_0" geometry={nodes['pCylinder83_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder83_blanc_0" geometry={nodes.pCylinder83_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="pCylinder83_beige_0" geometry={nodes.pCylinder83_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCylinder84" position={[-18.03, 46.82, 33.47]} rotation={[0, 0.61, 0]} scale={0.44}>
                  <mesh name="pCylinder84_jaune_0" geometry={nodes.pCylinder84_jaune_0.geometry} material={materials.jaune} />
                  <mesh name="pCylinder84_brun_fonc��_0" geometry={nodes['pCylinder84_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder84_vert_0" geometry={nodes.pCylinder84_vert_0.geometry} material={materials.vert} />
                  <mesh name="pCylinder84_vert_fonc��_0" geometry={nodes['pCylinder84_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pCylinder85" position={[-35.39, 52.57, 52.77]} rotation={[0, -0.76, 0]} scale={0.35}>
                  <mesh name="pCylinder85_bleu_0" geometry={nodes.pCylinder85_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="pCylinder85_brun_fonc��_0" geometry={nodes['pCylinder85_brun_fonc��_0'].geometry} material={materials.brun_fonc} />
                  <mesh name="pCylinder85_vert_0" geometry={nodes.pCylinder85_vert_0.geometry} material={materials.vert} />
                  <mesh name="pCylinder85_vert_fonc��_0" geometry={nodes['pCylinder85_vert_fonc��_0'].geometry} material={materials.vert_fonc} />
                </group>
                <group name="pCube157" position={[40.45, 60.75, -44.59]} scale={[0.13, 4.5, 0.06]}>
                  <mesh name="pCube157_noir_0" geometry={nodes.pCube157_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube158" position={[40.76, 60.56, -44.59]} rotation={[0, 0, -0.64]} scale={[0.09, 3.88, 0.06]}>
                  <mesh name="pCube158_noir_0" geometry={nodes.pCube158_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube159">
                  <mesh name="pCube159_noir_0" geometry={nodes.pCube159_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCylinder86" position={[37.63, 55.95, -34.05]} scale={[0.07, 0.07, 0.23]}>
                  <mesh name="pCylinder86_noir_0" geometry={nodes.pCylinder86_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube160">
                  <mesh name="pCube160_noir_0" geometry={nodes.pCube160_noir_0.geometry} material={materials.noir} />
                  <mesh name="pCube160_musique_0" geometry={nodes.pCube160_musique_0.geometry} material={materials.musique} />
                </group>
                <group name="Mesh12">
                  <mesh name="Mesh12_beige_0" geometry={nodes.Mesh12_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube163" position={[-12.14, 24.3, -20.66]} rotation={[-0.25, -0.73, -0.17]} scale={[11.82, 2.96, 0.65]}>
                  <mesh name="pCube163_beige_0" geometry={nodes.pCube163_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube164" position={[11.75, 24.08, -30.47]} scale={[35.74, 6.57, 4.51]}>
                  <mesh name="pCube164_beige_0" geometry={nodes.pCube164_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube165" position={[11.75, 15.4, -27.96]} scale={[35.74, 6.57, 4.51]}>
                  <mesh name="pCube165_beige_0" geometry={nodes.pCube165_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube166" position={[11.75, 7.04, -30.82]} scale={[35.74, 6.57, 4.51]}>
                  <mesh name="pCube166_beige_0" geometry={nodes.pCube166_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="pCube167" position={[-29.39, 24.1, -16.07]} rotation={[0, 0.08, 0]} scale={[4.52, 2.52, 15.32]}>
                  <mesh name="pCube167_noir_0" geometry={nodes.pCube167_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCube168" position={[-29.05, 22.94, -29.74]} rotation={[0, -0.15, 0]} scale={[5.5, 0.14, 5.5]}>
                  <mesh name="pCube168_turquoise_0" geometry={nodes.pCube168_turquoise_0.geometry} material={materials.turquoise} />
                </group>
                <group name="extrudedSurface17" position={[7.66, 6.75, -14.67]} rotation={[-0.02, 0, 1.6]} scale={[1, 2.95, 1.41]}>
                  <mesh name="extrudedSurface17_bleu_0" geometry={nodes.extrudedSurface17_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="extrudedSurface18" position={[-6.24, 4.95, -45.5]} rotation={[-3.11, -0.04, -1.59]} scale={[1.19, 2.7, 1.41]}>
                  <mesh name="extrudedSurface18_lila_0" geometry={nodes.extrudedSurface18_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="extrudedSurface19" position={[-4.49, -10.17, -51.38]} rotation={[-3.11, -0.04, -1.59]} scale={[2.65, 4.24, 1.87]}>
                  <mesh name="extrudedSurface19_bleu_0" geometry={nodes.extrudedSurface19_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="extrudedSurface20" position={[-16.7, 6.14, -24]} rotation={[3.01, -1.38, -1.68]} scale={[1.14, 2.57, 1.22]}>
                  <mesh name="extrudedSurface20_jaune_0" geometry={nodes.extrudedSurface20_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="extrudedSurface22" position={[6.96, 3.27, -44.28]} rotation={[-3.1, 0.03, -1.59]} scale={[1.37, 3.12, 1.28]}>
                  <mesh name="extrudedSurface22_jaune_0" geometry={nodes.extrudedSurface22_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="extrudedSurface23" position={[22.24, -5.44, -50.36]} rotation={[-3.09, 0.32, -1.6]} scale={[2.26, 2.65, 1.56]}>
                  <mesh name="extrudedSurface23_rose_0" geometry={nodes.extrudedSurface23_rose_0.geometry} material={materials.rose} />
                </group>
                <group name="pCube175" position={[-35.97, 53.02, 16.83]} scale={[21.32, 6.57, 11.58]}>
                  <mesh name="pCube175_beige_0" geometry={nodes.pCube175_beige_0.geometry} material={materials.beige} />
                </group>
                <group name="polySurface219" position={[-2.07, 21.51, 32.17]} rotation={[-Math.PI, 1.48, -Math.PI]}>
                  <mesh name="polySurface219_blanc_0" geometry={nodes.polySurface219_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface219_rose_0" geometry={nodes.polySurface219_rose_0.geometry} material={materials.rose} />
                  <mesh name="polySurface219_jaune_0" geometry={nodes.polySurface219_jaune_0.geometry} material={materials.jaune} />
                  <mesh name="polySurface219_lila_0" geometry={nodes.polySurface219_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="polySurface220" position={[-6.77, 18.89, 21.16]} rotation={[-Math.PI, 1.2, -Math.PI]} scale={[0.9, 1.15, 0.9]}>
                  <mesh name="polySurface220_blanc_0" geometry={nodes.polySurface220_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface220_bleu_0" geometry={nodes.polySurface220_bleu_0.geometry} material={materials.bleu} />
                  <mesh name="polySurface220_lila_0" geometry={nodes.polySurface220_lila_0.geometry} material={materials.lila} />
                </group>
                <group name="polySurface221" position={[9.23, -12.61, -9.62]} scale={1.25}>
                  <group name="polySurface258">
                    <mesh name="polySurface258_rose_0" geometry={nodes.polySurface258_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface259">
                    <mesh name="polySurface259_rose_0" geometry={nodes.polySurface259_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface260">
                    <mesh name="polySurface260_rose_0" geometry={nodes.polySurface260_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface261">
                    <mesh name="polySurface261_rose_0" geometry={nodes.polySurface261_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface262">
                    <mesh name="polySurface262_turquoise_0" geometry={nodes.polySurface262_turquoise_0.geometry} material={materials.turquoise} />
                  </group>
                  <group name="polySurface263">
                    <mesh name="polySurface263_turquoise_0" geometry={nodes.polySurface263_turquoise_0.geometry} material={materials.turquoise} />
                    <mesh name="polySurface263_pasted__turquoise_0" geometry={nodes.polySurface263_pasted__turquoise_0.geometry} material={materials.pasted__turquoise} />
                    <mesh name="polySurface263_rose_0" geometry={nodes.polySurface263_rose_0.geometry} material={materials.rose} />
                  </group>
                  <group name="polySurface264">
                    <mesh name="polySurface264_turquoise_0" geometry={nodes.polySurface264_turquoise_0.geometry} material={materials.turquoise} />
                  </group>
                  <group name="polySurface265">
                    <mesh name="polySurface265_rose_0" geometry={nodes.polySurface265_rose_0.geometry} material={materials.rose} />
                    <mesh name="polySurface265_pasted__rose_0" geometry={nodes.polySurface265_pasted__rose_0.geometry} material={materials.pasted__rose} />
                  </group>
                </group>
                <group name="pCube176" position={[-2.41, -48.98, -33.99]} rotation={[0, 0.46, 0]}>
                  <mesh name="pCube176_bleu_0" geometry={nodes.pCube176_bleu_0.geometry} material={materials.bleu} />
                </group>
                <group name="pPlatonic9" position={[-35.84, 23.85, 5.62]} rotation={[0, 0, -0.35]} scale={1.25}>
                  <mesh name="pPlatonic9_blanc_0" geometry={nodes.pPlatonic9_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlatonic10" position={[-32.44, 23.52, 3.04]} rotation={[0, 0, -0.35]} scale={0.83}>
                  <mesh name="pPlatonic10_blanc_0" geometry={nodes.pPlatonic10_blanc_0.geometry} material={materials.blanc} />
                </group>
                <group name="pPlane12" position={[-8.15, 7.06, 8.96]} rotation={[-0.26, -0.1, -0.17]}>
                  <mesh name="pPlane12_jaune_0" geometry={nodes.pPlane12_jaune_0.geometry} material={materials.jaune} />
                </group>
                <group name="polySurface231" position={[-23.38, -3.33, -19.84]}>
                  <mesh name="polySurface231_blanc_0" geometry={nodes.polySurface231_blanc_0.geometry} material={materials.blanc} />
                  <mesh name="polySurface231_beige_0" geometry={nodes.polySurface231_beige_0.geometry} material={materials.beige} />
                  <mesh name="polySurface231_rose_0" geometry={nodes.polySurface231_rose_0.geometry} material={materials.rose} />
                  <mesh name="polySurface231_pasted__rose_0" geometry={nodes.polySurface231_pasted__rose_0.geometry} material={materials.pasted__rose} />
                </group>
                <group name="locAlign_pCube182" position={[-36.2, 60.59, 38.23]} rotation={[1.4, 0.3, 1.09]} scale={0.54}>
                  <group name="pCube182" rotation={[0, Math.PI / 10, 0]}>
                    <mesh name="pCube182_blanc_0" geometry={nodes.pCube182_blanc_0.geometry} material={materials.blanc} />
                  </group>
                </group>
                <group name="extrudedSurface25" position={[-45.7, 28.01, -54.97]} rotation={[0, -0.3, 0]}>
                  <mesh name="extrudedSurface25_noir_0" geometry={nodes.extrudedSurface25_noir_0.geometry} material={materials.noir} />
                </group>
                <group name="pCylinder95" position={[-1.7, -0.04, -0.96]}>
                  <mesh name="pCylinder95_noir_0" geometry={nodes.pCylinder95_noir_0.geometry} material={materials.noir} />
                  <mesh name="pCylinder95_beige_0" geometry={nodes.pCylinder95_beige_0.geometry} material={materials.beige} />
                  <mesh name="pCylinder95_blanc_0" geometry={nodes.pCylinder95_blanc_0.geometry} material={materials.blanc} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.gltf')
