/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Morganicism (https://sketchfab.com/morganicism)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spyro-the-dragon-d60585b995d84e6f93e8793614058aa0
title: Spyro The Dragon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/spyro.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 4, 1.34]} rotation={[1.52, 0, 0]} scale={.65}>
          <primitive object={nodes.Armature_rootJoint} />
          <group position={[0, 2.2, 1.22]} rotation={[-1.52, 0, 0]}>
            <group position={[0, 0.93, -2.92]} scale={0.19}>
              <mesh geometry={nodes.wings_1.geometry} material={materials['Material.009']} />
            </group>
            <group position={[0, 6.6, -2.52]} scale={0.4}>
              <mesh geometry={nodes.tail_spike_1.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0, 1.12, -1.21]} scale={0.18}>
              <mesh geometry={nodes.spine_1.geometry} material={materials['Material.006']} />
            </group>
            <group position={[0, -0.58, -0.7]} rotation={[-2.93, 0, -Math.PI]} scale={[0.15, 0.12, 0.09]}>
              <mesh geometry={nodes.lower_teeth_1.geometry} material={materials['Material.004']} />
            </group>
            <group position={[0, -0.24, -0.58]} rotation={[0.16, 0, 0]} scale={[0.33, 0.48, 0.13]}>
              <mesh geometry={nodes.tongue_1.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0, -0.72, -0.44]} rotation={[0.31, 0, 0]} scale={[0.15, 0.12, 0.09]}>
              <mesh geometry={nodes.upper_teeth_1.geometry} material={materials['Material.004']} />
            </group>
            <group position={[0, -0.04, 0]} rotation={[0.19, 0, 0]} scale={0.9}>
              <mesh geometry={nodes.eyes_1.geometry} material={materials['Material.001']} />
            </group>
            <group position={[0, 2.42, -2.86]}>
              <mesh geometry={nodes.horns_1.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0, 0.83, 1.16]} scale={1.23}>
              <mesh geometry={nodes.Crest_1.geometry} material={materials['Material.002']} />
            </group>
            <mesh geometry={nodes.spyro_1.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spyro.gltf')
