/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: riikkakilpelainen (https://sketchfab.com/riikkakilpelainen)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/the-botanists-study-8b7b5743b1c848ed8ea58f5518c44e7e
title: The Botanist's Study
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Study(props) {
  const { nodes, materials } = useGLTF('/study.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Room_M_Room_0.geometry} material={materials.M_Room} />
            <mesh geometry={nodes.Room_M_Furniture_0.geometry} material={materials.M_Furniture} />
            <mesh geometry={nodes.Room_M_Decorations_0.geometry} material={materials.M_Decorations} />
            <mesh geometry={nodes.Room_M_Glass_0.geometry} material={materials.M_Glass} />
            <mesh geometry={nodes.Room_M_Light_0.geometry} material={materials.M_Light} />
            <mesh geometry={nodes.Room_M_Cutout_0.geometry} material={materials.M_Cutout} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.VolumetricLight001_M_VolumetricLight_0.geometry} material={materials.M_VolumetricLight} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/study.gltf')
